totem {
  version: 2
  cluster_name: pgsql-pcmk
  transport: knet
  crypto_cipher: none
  crypto_hash: none
  token: 3000
  consensus: 3600
}

nodelist {
  node {
    ring0_addr: 172.31.110.11
    name: db1
    nodeid: 1
  }
  node {
    ring0_addr: 172.31.110.12
    name: db2
    nodeid: 2
  }
}

quorum {
  provider: corosync_votequorum
  two_node: 1
  wait_for_all: 1
}

logging {
  to_stderr: yes
  to_logfile: yes
  logfile: /var/log/corosync/corosync.log
  timestamp: on
}
