name: pgsql-ha-witness

services:
  etcd:
    container_name: pgsql-ha-etcd-witness
    image: gcr.io/etcd-development/etcd:v3.5.21
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${ETCD_DATA_DIR:?set ETCD_DATA_DIR}:/etcd-data
    command:
      - /usr/local/bin/etcd
      - --name=etcd3
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://${NODE_IP:?set NODE_IP}:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://${NODE_IP}:2380
      - --initial-cluster=${ETCD_INITIAL_CLUSTER:?set ETCD_INITIAL_CLUSTER}
      - --initial-cluster-state=new
      - --initial-cluster-token=${ETCD_CLUSTER_TOKEN:?set ETCD_CLUSTER_TOKEN}
      - --auto-compaction-retention=1
      - --auto-compaction-mode=periodic
